services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: docker/Dockerfile
    networks:
      - algo-app
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN:?error}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable

  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_DB: ${POSTGRES_DB:-master}
    networks:
      - algo-app
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "6000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-master}"]
      interval: 5s
      timeout: 5s
      retries: 5


  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - algo-app
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path=/migrations",
        "-database=postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:?error}@db:5432/${POSTGRES_DB:-master}?sslmode=disable",
        "up"
      ]

volumes:
  postgres-data:

networks:
  algo-app:
    driver: bridge

