ALTER TABLE algo_tasks
ADD COLUMN review_count INTEGER NOT NULL DEFAULT 1,
ADD COLUMN last_reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
ADD COLUMN next_review_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
